vocabulary = [
{"el": "der"},
{"es": "ist"},
{"no": "nein"},
{"un": "ein"},
{"una": "eine"},
{"yo": "ich"},
{"se": "sich"},
{"pero": "aber"},
{"mi": "mein"},
{"para": "für"},
{"el": "der"},
{"es": "ist"},
{"no": "nein"},
{"un": "ein"},
{"una": "eine"},
{"yo": "ich"},
{"se": "sich"},
{"pero": "aber"},
{"mi": "mein"},
{"para": "für"},
{"con": "mit"},
{"está": "ist"},
{"por": "durch"},
{"los": "die"},
{"las": "die"},
{"como": "wie"},
{"le": "ihm"},
{"lo": "es"},
{"todo": "alles"},
{"más": "mehr"},
{"ya": "bereits"},
{"o": "oder"},
{"al": "zum"},
{"cómo": "wie"},
{"me": "mir"},
{"este": "dies"},
{"si": "wenn"},
{"te": "dir"},
{"esos": "diese"},
{"así": "so"},
{"nada": "nichts"},
{"sí": "ja"},
{"nos": "uns"},
{"tiene": "hat"},
{"él": "er"},
{"bien": "gut"},
{"esa": "diese"},
{"y": "und"},
{"desde": "seit"},
{"hasta": "bis"},
{"fuera": "aus"},
{"quiero": "ich möchte"},
{"cuando": "wenn"},
{"aqui": "hier"},
{"mejor": "besser"},
{"siempre": "immer"},
{"puedo": "ich kann"},
{"solo": "allein"},
{"ella": "sie"},
{"creo": "glaube"},
{"mucho": "viel"},
{"vez": "mal"},
{"antes": "vor"},
{"todos": "alle"},
{"dos": "zwei"},
{"pues": "also"},
{"ser": "sein"},
{"aunque": "obwohl"},
{"ahora": "jetzt"},
{"tengo": "ich habe"},
{"nunca": "nie"},
{"aquí": "hier"},
{"hay": "es gibt"},
{"hacer": "machen"},
{"he": "habe"},
{"esto": "dieses"},
{"porque": "weil"},
{"este": "dieser"},
{"tú": "du"},
{"quieres": "du möchtest"},
{"mismo": "gleich"},
{"sobre": "über"},
{"sé": "ich weiß"},
{"ti": "dich"},
{"será": "wird sein"},
{"donde": "wo"},
{"tienes": "du hast"},
{"eso": "dies"},
{"nosotros": "wir"},
{"hacia": "in Richtung"},
{"dónde": "wohin"},
{"han": "haben"},
{"gracias": "danke"},
{"nuevo": "neu"},
{"bueno": "gut"},
{"menos": "weniger"},
{"aún": "noch"},
{"sólo": "nur"},
{"después": "nach"},
{"quién": "wer"},
{"dice": "sagt"},
{"mundo": "Welt"},
{"cuando": "wann"},
{"fuera": "draußen"},
{"gran": "groß"},
{"sabe": "weiß"},
{"tener": "haben"},
{"hoy": "heute"},
{"estoy": "ich bin"},
{"mucho": "sehr"},
{"dar": "geben"},
{"misma": "gleiche"},
{"años": "Jahre"},
{"vamos": "wir gehen"},
{"ver": "sehen"},
{"hombre": "Mann"},
{"hey": "Hallo"},
{"grande": "groß"},
{"señor": "Herr"},
{"buen": "gut"},
{"aquella": "jener"},
{"vez": "Zeit"},
{"donde": "wohin"},
{"vida": "Leben"},
{"tener": "haben"},
{"hijos": "Kinder"},
{"dijo": "sagte"},
{"tu": "dein"},
{"nuestro": "unser"},
{"rato": "Weile"},
{"hombro": "Schulter"},
{"cada": "jeder"},
{"día": "Tag"},
{"hijo": "Sohn"},
{"todas": "alle"},
{"cielo": "Himmel"},
{"puerta": "Tür"},
{"podemos": "wir können"},
{"juntos": "gemeinsam"},
{"madre": "Mutter"},
{"problema": "Problem"},
{"aquel": "jener"},
{"mil": "tausend"},
{"mano": "Hand"},
{"tenemos": "wir haben"},
{"hace": "vor"},
{"niños": "Kinder"},
{"padre": "Vater"},
{"mis": "meine"},
{"ciudad": "Stadt"},
{"parte": "Teil"},
{"hacia": "in Richtnug"},
{"hombres": "Männer"},
{"nada": "nichts"},
{"hacen": "sie machen"},
{"seguro": "sicher"},
{"nosotras": "wir"},
{"espera": "Warte"},
{"hijos": "Kinder"},
{"aquel": "jener"},
{"verdad": "Wahrheit"},
{"semana": "Woche"},
{"estos": "diese"},
{"nombre": "Name"},
{"estar": "sein"},
{"mujer": "Frau"},
{"historia": "Geschichte"},
{"tan": "so"},
{"dijo": "sagte"},
{"sabe": "weiß"},
{"esos": "diese"},
{"días": "Tage"},
{"dios": "Gott"},
{"tenido": "gehabt"},
{"pueden": "sie können"},
{"niña": "Mädchen"},
{"hemos": "wir haben"},
{"tienen": "sie haben"},
{"años": "Jahre"},
{"amigo": "Freund"},
{"salir": "gehen"},
{"meses": "Monate"},
{"trabajo": "Arbeit"},
{"aún": "noch"},
{"niños": "Kinder"},
{"gran": "großartig"},
{"escuela": "Schule"},
{"vino": "Wein"},
{"hacia": "in Richtung"},
{"padres": "Eltern"},
{"dices": "du sagst"},
{"año": "Jahr"},
{"quien": "wer"},
{"aunque": "obwohl"},
{"niño": "Junge"},
{"jugar": "spielen"},
{"general": "generell"},
{"apenas": "kaum"},
{"aquella": "jene"},
{"nivel": "Niveau"},
{"historia": "Geschichte"},
{"decir": "sagen"},
{"cada": "jeder"},
{"diré": "ich werde sagen"},
{"seguir": "folgen"},
{"hijos": "Kinder"},
{"sola": "allein"},
{"puedo": "ich kann"},
{"incluso": "sogar"},
{"encontrar": "finden"},
{"solo": "allein"},
{"tarde": "spät"},
{"aquel": "jener"},
{"hora": "Stunde"},
{"vida": "Leben"},
{"aunque": "obwohl"},
{"puedes": "du kannst"},
{"pronto": "bald"},
{"niño": "Junge"},
{"sabes": "du weißt"},
{"pregunta": "Frage"},
{"veces": "Mal"},
{"coche": "Auto"},
{"será": "wird sein"},
{"razón": "Grund"},
{"siquiera": "nicht einmal"},
{"joven": "jung"},
{"necesito": "ich brauche"},
{"menos": "weniger"},
{"estaba": "war"},
{"hacia": "in Richtung"},
{"aquellos": "jene"},
{"amigos": "Freunde"},
{"quiere": "er/sie will"},
{"espera": "Warte"},
{"cuenta": "Rechnung"},
{"problemas": "Probleme"},
{"juega": "er/sie spielt"},
{"casa": "Haus"},
{"estoy": "ich bin"},
{"ultima": "letzte"},
{"gusto": "Geschmack"},
{"señor": "Herr"},
{"donde": "wo"},
{"dio": "gab"},
{"sigue": "folge"},
{"hecho": "gemacht"},
{"después": "nach"},
{"tal": "solch"},
{"déjame": "lass mich"},
{"salir": "verlassen"},
{"último": "letzter"},
{"usar": "benutzen"},
{"mes": "Monat"},
{"aquel": "jener"},
{"través": "durch"},
{"pueden": "sie können"},
{"partir": "teilen"},
{"señora": "Dame"},
{"estaré": "ich werde sein"},
{"sabe": "er/sie weiß"},
{"madre": "Mutter"},
{"quién": "wer"},
{"seguro": "sicher"},
{"sillas": "Stühle"},
{"grande": "groß"},
{"tipo": "Art"},
{"desde": "von"},
{"tener": "haben"},
{"problemas": "Probleme"},
{"poder": "können"},
{"comer": "essen"},
{"mejor": "besser"},
{"joven": "jung"},
{"sentar": "sitzen"},
{"salud": "Gesundheit"},
{"caso": "Fall"},
{"minutos": "Minuten"},
{"digo": "ich sage"},
{"dan": "sie geben"},
{"tiempo": "Zeit"},
{"alguna": "irgendeine"},
{"estás": "du bist"},
{"sabe": "er/sie weiß"},
{"mañana": "Morgen"},
{"cuestión": "Frage"},
{"parte": "Teil"},
{"padre": "Vater"},
{"gente": "Leute"},
{"tanto": "so viel"},
{"niño": "Junge"},
{"puedo": "ich kann"},
{"punto": "Punkt"},
{"entre": "zwischen"},
{"lado": "Seite"},
{"podemos": "wir können"},
{"otra": "andere"},
{"puedo": "ich kann"},
{"necesito": "ich brauche"},
{"nunca": "nie"},
{"casa": "Haus"},
{"cosa": "Sache"},
{"hombre": "Mann"},
{"mucho": "viel"},
{"ahí": "da"},
{"ahora": "jetzt"},
{"dará": "wird geben"},
{"aquellos": "jene"},
{"algunos": "einige"},
{"aún": "noch"},
{"forma": "Form"},
{"fuera": "draußen"},
{"menos": "weniger"},
{"hacia": "in Richtung"},
{"puedo": "ich kann"},
{"lejos": "weit"},
{"siempre": "immer"},
{"cada": "jeder"},
{"quieres": "du möchtest"},
{"dad": "Vater"},
{"primero": "erstes"},
{"hijo": "Sohn"},
{"tal": "solch"},
{"entre": "zwischen"},
{"sabe": "er/sie weiß"},
{"aquel": "jener"},
{"razón": "Grund"},
{"puedes": "du kannst"},
{"pensar": "denken"},
{"sabe": "weiß"},
{"manera": "Art"},
{"solo": "allein"},
{"pueden": "sie können"},
{"duda": "Zweifel"},
{"verdad": "Wahrheit"},
{"mejor": "besser"},
{"hablar": "sprechen"},
{"mirar": "schauen"},
{"sin": "ohne"},
{"visto": "gesehen"},
{"dame": "gib mir"},
{"hombres": "Männer"},
{"sí": "ja"},
{"idea": "Idee"},
{"después": "nach"},
{"luz": "Licht"},
{"quiere": "er/sie will"},
{"niño": "Kind"},
{"problema": "Problem"},
{"señora": "Dame"},
{"conozco": "ich kenne"},
{"espero": "ich hoffe"},
{"quieren": "sie wollen"},
{"niños": "Kinder"},
{"saben": "sie wissen"},
{"cuanto": "so viel"},
{"mantener": "halten"},
{"aquel": "jener"},
{"fuera": "draußen"},
{"aquí": "hier"},
{"donde": "wo"},
{"da": "gibt"},
{"hora": "Stunde"},
{"voy": "ich gehe"},
{"algún": "irgendein"},
{"aquellos": "jene"},
{"partir": "teilen"},
{"llamar": "anrufen"},
{"iremos": "wir werden gehen"},
{"estaré": "ich werde sein"},
{"pregunta": "Frage"},
{"digo": "ich sage"},
{"aquel": "jener"},
{"algo": "etwas"},
{"mujer": "Frau"},
{"debe": "sollte"},
{"mucho": "sehr"},
{"también": "auch"},
{"nuestra": "unsere"},
{"buen": "gut"},
{"será": "es wird sein"},
{"hoy": "heute"},
{"primera": "erste"},
{"manos": "Hände"},
{"hacemos": "wir machen"},
{"probablemente": "wahrscheinlich"},
{"mayor": "größer"},
{"pensé": "ich dachte"},
{"oído": "gehört"},
{"tema": "Thema"},
{"amor": "Liebe"},
{"hacia": "in Richtung"},
{"hijo": "Kind"},
{"preguntar": "fragen"},
{"vamos": "wir gehen"},
{"misma": "gleiche"},
{"todavía": "noch"},
{"suerte": "Glück"},
{"aquel": "jener"},
{"puerta": "Tür"},
{"hermano": "Bruder"},
{"puedo": "ich kann"},
{"alguna": "irgendeine"},
{"familia": "Familie"},
{"mío": "mein"},
{"miembros": "Mitglieder"},
{"amigos": "Freunde"},
{"otras": "andere"},
{"amor": "Liebe"},
{"mujeres": "Frauen"},
{"totalmente": "vollständig"},
{"niño": "Junge"},
{"ciertos": "bestimmte"},
{"niños": "Kinder"},
{"poder": "können"},
{"basado": "basierend auf"},
{"mañana": "Morgen"},
{"parece": "es scheint"},
{"valor": "Wert"},
{"pasa": "passiert"},
{"propio": "eigen"},
{"historia": "Geschichte"},
{"hacen": "sie machen"},
{"cabeza": "Kopf"},
{"dijo": "sagte"},
{"palabra": "Wort"},
{"más": "mehr"},
{"estaba": "war"},
{"debería": "sollte"},
{"puede": "es kann"},
{"saben": "sie wissen"},
{"aquel": "jener"},
{"sabe": "er/sie weiß"},
{"gran": "großartig"},
{"tipo": "Art"},
{"amor": "Liebe"},
{"gracias": "danke"},
{"pasar": "verbringen"},
{"cierto": "sicher"},
{"puedo": "ich kann"},
{"dicho": "gesagt"},
{"señor": "Herr"},
{"aquella": "jene"},
{"base": "Basis"},
{"hijos": "Kinder"},
{"habrá": "es wird geben"},
{"hacen": "sie machen"},
{"cuatro": "vier"},
{"haber": "haben"},
{"país": "Land"},
{"algunos": "einige"},
{"puedes": "du kannst"},
{"amigos": "Freunde"},
{"llama": "ruft"},
{"necesita": "er/sie braucht"},
{"parar": "stoppen"},
{"aquel": "jener"},
{"quieren": "sie wollen"},
{"niño": "Junge"},
{"nombre": "Name"},
{"hacerlo": "es tun"},
{"pequeño": "klein"},
{"dentro": "innerhalb"},
{"aquel": "jener"},
{"miembros": "Mitglieder"},
{"educación": "Bildung"},
{"parece": "es scheint"},
{"tiempo": "Zeit"},
{"lugar": "Ort"},
{"deja": "lass es"},
{"menos": "weniger"},
{"esos": "diese"},
{"sabe": "er/sie weiß"},
{"hijo": "Kind"},
{"posible": "möglich"},
{"quién": "wer"},
{"hablando": "sprechen"},
{"corazón": "Herz"},
{"será": "es wird sein"},
{"quiere": "er/sie will"},
{"este": "dieser"},
{"señora": "Dame"},
{"importante": "wichtig"},
{"hacia": "in Richtung"},
{"niño": "Junge"},
{"dicho": "gesagt"},
{"hace": "vor"},
{"aquel": "jener"},
{"ciudad": "Stadt"},
{"manera": "Art"},
{"hacen": "sie machen"},
{"justo": "gerecht"},
{"mundo": "Welt"},
{"sobre": "über"},
{"hijos": "Kinder"},
{"sabe": "er/sie weiß"},
{"ustedes": "ihr"},
{"tiempo": "Zeit"},
{"saben": "sie wissen"},
{"hijo": "Kind"},
{"aquella": "jene"},
{"dentro": "innerhalb"},
{"hace": "vor"},
{"pregunta": "Frage"},
{"hola": "Hallo"},
{"mucho": "viel"},
{"alguna": "irgendeine"},
{"estaré": "ich werde sein"},
{"forma": "Form"},
{"visto": "gesehen"},
{"tierra": "Erde"},
{"seguro": "sicher"},
{"vida": "Leben"},
{"sólo": "nur"},
{"vale": "in Ordnung"},
{"hombre": "Mann"},
{"palabras": "Wörter"},
{"verdad": "Wahrheit"},
{"donde": "wo"},
{"probar": "probieren"},
{"buena": "gut"},
{"ciudad": "Stadt"},
{"minutos": "Minuten"},
{"dijo": "sagte"},
{"necesita": "er/sie braucht"},
{"trabajo": "Arbeit"},
{"manos": "Hände"},
{"sucede": "geschieht"},
{"pequeña": "klein"},
{"cosa": "Sache"},
{"quiere": "er/sie will"},
{"dicho": "gesagt"},
{"sigue": "folge"},
{"pasa": "passiert"},
{"mejor": "besser"},
{"usted": "Sie"},
{"momento": "Moment"},
{"puedes": "du kannst"},
{"tendrá": "er/sie wird haben"},
{"mundo": "Welt"},
{"continuar": "weitermachen"},
{"ojos": "Augen"},
{"hacia": "in Richtung"},
{"realidad": "Realität"},
{"ven": "komm"},
{"cielo": "Himmel"},
{"parece": "es scheint"},
{"desde": "von"},
{"personas": "Personen"},
{"marido": "Ehemann"},
{"algunos": "einige"},
{"entonces": "dann"},
{"algunas": "einige"},
{"casa": "Haus"},
{"aunque": "obwohl"},
{"alguien": "jemand"},
{"culpa": "Schuld"},
{"sido": "gewesen"},
{"hombre": "Mann"},
{"menos": "weniger"},
{"gran": "groß"},
{"historia": "Geschichte"},
{"cielo": "Himmel"},
{"buenas": "gute"},
{"dicho": "gesagt"},
{"aquellos": "jene"},
{"mayor": "größer"},
{"hombres": "Männer"},
{"dos": "zwei"},
{"venido": "gekommen"},
{"seguro": "sicher"},
{"habrá": "es wird geben"},
{"familia": "Familie"},
{"verá": "er/sie wird sehen"},
{"vivir": "leben"},
{"problemas": "Probleme"},
{"lejos": "weit"},
{"personas": "Personen"},
{"meses": "Monate"},
{"contra": "gegen"},
{"hace": "vor"},
{"mismo": "gleich"},
{"algún": "irgendein"},
{"ahora": "jetzt"},
{"mejor": "besser"},
{"mira": "sieh"},
{"madre": "Mutter"},
{"casa": "Haus"},
{"pueda": "er/sie kann"},
{"puedo": "ich kann"},
{"verla": "sieh"},
{"días": "Tage"},
{"gran": "großartig"},
{"chica": "Mädchen"},
{"salir": "verlassen"},
{"hijos": "Kinder"},
{"puntos": "Punkte"},
{"sentido": "Gefühl"},
{"niños": "Kinder"},
{"padre": "Vater"},
{"aquel": "jener"},
{"aunque": "obwohl"},
{"palabras": "Wörter"},
{"seguridad": "Sicherheit"},
{"aquí": "hier"},
{"misma": "gleiche"},
{"dinero": "Geld"},
{"aquel": "jener"},
{"mientras": "während"},
{"bueno": "gut"},
{"cosas": "Dinge"},
{"madre": "Mutter"},
{"padres": "Eltern"},
{"quiera": "er/sie möchte"},
{"tendrá": "er/sie wird haben"},
{"sino": "sondern"},
{"dentro": "innerhalb"},
{"problema": "Problem"},
{"niños": "Kinder"},
{"hablan": "sie sprechen"},
{"haciendo": "machend"},
{"todas": "alle"},
{"pueden": "sie können"},
{"aquel": "jener"},
{"dicho": "gesagt"},
{"seguir": "folgen"},
{"punto": "Punkt"},
{"decir": "sagen"},
{"día": "Tag"},
{"hombres": "Männer"},
{"historia": "Geschichte"},
{"alguna": "irgendeine"},
{"vida": "Leben"},
{"hace": "vor"},
{"aquellos": "jene"},
{"siempre": "immer"},
{"paso": "Schritt"},
{"algunos": "einige"},
{"hacerlo": "es tun"},
{"madre": "Mutter"},
{"mujer": "Frau"},
{"manera": "Art"},
{"hasta": "bis"},
{"menos": "weniger"},
{"hijos": "Kinder"},
{"aquella": "jene"},
{"sido": "gewesen"},
{"parece": "es scheint"},
{"donde": "wo"},
{"poder": "können"},
{"señora": "Dame"},
{"horas": "Stunden"},
{"seguir": "folgen"},
{"desde": "von"},
{"hacia": "in Richtung"},
{"hijos": "Kinder"},
{"cada": "jeder"},
{"aquellas": "jene"},
{"persona": "Person"},
{"mayor": "größer"},
{"niños": "Kinder"},
{"diciendo": "sagen"},
{"mujer": "Frau"},
{"esto": "dies"},
{"aquello": "jenes"},
{"aquel": "jener"},
{"mismo": "gleich"},
{"puntos": "Punkte"},
{"vida": "Leben"},
{"parte": "Teil"},
{"partes": "Teile"},
{"prueba": "Test"},
{"niños": "Kinder"},
{"hace": "vor"},
{"dicen": "sie sagen"},
{"seguridad": "Sicherheit"},
{"problema": "Problem"},
{"menos": "weniger"},
{"punto": "Punkt"},
{"aquel": "jener"},
{"fuerza": "Kraft"},
{"hasta": "bis"},
{"primer": "erstes"},
{"problemas": "Probleme"},
{"tiempos": "Zeiten"},
{"chica": "Mädchen"},
{"cierto": "sicher"},
{"familia": "Familie"},
{"hijo": "Sohn"},
{"aquellos": "jene"},
{"manera": "Art"},
{"fuera": "draußen"},
{"bueno": "gut"},
{"ojos": "Augen"},
{"esos": "diese"},
{"casa": "Haus"},
{"padres": "Eltern"},
{"tiempo": "Zeit"},
{"menos": "weniger"},
{"forma": "Form"},
{"parece": "es scheint"},
{"claro": "klar"},
{"aquel": "jener"},
{"vamos": "wir gehen"},
{"hablo": "ich spreche"},
{"siete": "sieben"},
{"será": "es wird sein"},
{"algunas": "einige"},
{"aquel": "jener"},
{"qué": "was"},
{"punto": "Punkt"},
{"hacia": "in Richtung"},
{"aquellos": "jene"},
{"hombre": "Mann"},
{"hijo": "Kind"},
{"señor": "Herr"},
{"realidad": "Realität"},
{"hacen": "sie machen"},
{"personas": "Personen"},
{"seguro": "sicher"},
{"señora": "Dame"},
{"aquella": "jene"},
{"quiere": "er/sie will"},
{"punto": "Punkt"},
{"parece": "es scheint"},
{"durante": "während"},
{"parte": "Teil"},
{"dame": "gib mir"},
{"primer": "erstes"},
{"hermano": "Bruder"},
{"quiere": "er/sie will"},
{"hablar": "sprechen"},
{"problema": "Problem"},
{"hasta": "bis"},
{"mejor": "besser"},
{"nosotros": "wir"},
{"forma": "Form"},
{"fuerza": "Kraft"},
{"luz": "Licht"},
{"saber": "wissen"},
{"aquel": "jener"},
{"hablando": "sprechend"},
{"pueden": "sie können"},
{"aquellas": "jene"},
{"parece": "es scheint"},
{"hermano": "Bruder"},
{"mucho": "viel"},
{"marido": "Ehemann"},
{"padres": "Eltern"},
{"puntos": "Punkte"},
{"vamos": "wir gehen"},
{"quiere": "er/sie will"},
{"trabajo": "Arbeit"},
{"historia": "Geschichte"},
{"esas": "diese"},
{"hombres": "Männer"},
{"ojos": "Augen"},
{"parece": "es scheint"},
{"menos": "weniger"},
{"hijo": "Kind"},
{"personas": "Personen"},
{"aquel": "jener"},
{"hablar": "sprechen"},
{"quieres": "du möchtest"},
{"caso": "Fall"},
{"mujer": "Frau"},
{"hago": "ich mache"},
{"mujer": "Frau"},
{"amigos": "Freunde"},
{"buenas": "gute"},
{"partir": "teilen"},
{"seguro": "sicher"},
{"aquel": "jener"},
{"historia": "Geschichte"},
{"mayor": "größer"},
{"quién": "wer"},
{"amigo": "Freund"},
{"bueno": "gut"},
{"seguir": "folgen"},
{"tienen": "sie haben"},
{"casa": "Haus"},
{"aquellas": "jene"},
{"tiempo": "Zeit"},
{"hasta": "bis"},
{"niños": "Kinder"},
{"hacia": "in Richtung"},
{"importante": "wichtig"},
{"sabe": "er/sie weiß"},
{"hacerlo": "es tun"},
{"aquella": "jene"},
{"gran": "großartig"},
{"punto": "Punkt"},
{"vida": "Leben"},
{"nuestros": "unsere"},
{"señora": "Dame"},
// ... (fortsetzen bis zum 1000. Wort)
];
  
document.getElementById('start-learning').addEventListener('click', startLearning);
document.getElementById('flip-card').addEventListener('click', flipCard);
document.getElementById('next-card').addEventListener('click', nextCard);
document.getElementById('restart').addEventListener('click', restartLearning);

let start, end, direction, wordDisplay, currentWordIndex, currentWord;

function startLearning() {
    start = parseInt(document.getElementById('start').value);
    end = parseInt(document.getElementById('end').value);
    direction = document.querySelector('input[name="direction"]:checked').value;
    wordDisplay = document.getElementById('word-display');
    currentWordIndex = start;

    showWord();
}

function showWord() {
    if (currentWordIndex >= end) {
        document.getElementById('completion-area').style.display = 'block';
        return;
    }

    currentWord = vocabulary[currentWordIndex];
    if (direction === 'sp_to_ge') {
        wordDisplay.textContent = Object.keys(currentWord)[0]; // Gets the "spanish word"
    } else {
        wordDisplay.textContent = currentWord[Object.keys(currentWord)[0]]; // Gets the "german word"
    }
}

function flipCard() {
    if (currentWord) {
        if (wordDisplay.textContent === Object.keys(currentWord)[0]) {
            wordDisplay.textContent = currentWord[Object.keys(currentWord)[0]];
        } else {
            wordDisplay.textContent = Object.keys(currentWord)[0];
        }
    }
}

function nextCard() {
    currentWordIndex++;
    showWord();
}

function restartLearning() {
    currentWordIndex = start;
    document.getElementById('completion-area').style.display = 'none';
    showWord();
}
