let vocabulary = 
[
{"mundo": "Welt"},
{"cielo": "Himmel"},
{"pensar": "denken"},
{"luz": "Licht"},
{"estaba": "war"},
{"tiene": "er/sie hat"},
{"te": "dir"},
{"señor": "Herr"},
{"cuatro": "vier"},
{"debería": "sollte"},
{"partes": "Teile"},
{"tenido": "gehabt"},
{"tierra": "Erde"},
{"corazón": "Herz"},
{"algún": "irgendein"},
{"esas": "diese"},
{"niños": "Kinder"},
{"así": "so"},
{"usar": "benutzen"},
{"prueba": "Test"},
{"siempre": "immer"},
{"han": "haben"},
{"hijo": "Kind"},
{"cuando": "wann"},
{"cuenta": "Rechnung"},
{"nosotros": "wir"},
{"mano": "Hand"},
{"todo": "alles"},
{"hey": "Hallo"},
{"dicen": "sie sagen"},
{"creo": "glaube"},
{"conozco": "ich kenne"},
{"le": "ihm"},
{"salir": "gehen"},
{"joven": "jung"},
{"saben": "sie wissen"},
{"realidad": "Realität"},
{"último": "letzter"},
{"sobre": "über"},
{"basado": "basierend auf"},
{"este": "dies"},
{"primero": "erstes"},
{"cabeza": "Kopf"},
{"sucede": "geschieht"},
{"ciertos": "bestimmte"},
{"quiero": "ich möchte"},
{"otras": "andere"},
{"justo": "gerecht"},
{"aquella": "jener"},
{"manos": "Hände"},
{"algunos": "einige"},
{"veces": "Mal"},
{"tarde": "spät"},
{"dará": "wird geben"},
{"parece": "es scheint"},
{"chica": "Mädchen"},
{"hermano": "Bruder"},
{"dentro": "innerhalb"},
{"pasa": "passiert"},
{"coche": "Auto"},
{"mil": "tausend"},
{"padres": "Eltern"},
{"gran": "groß"},
{"estoy": "ich bin"},
{"valor": "Wert"},
{"tú": "du"},
{"ultima": "letzte"},
{"marido": "Ehemann"},
{"hora": "Stunde"},
{"si": "wenn"},
{"será": "wird sein"},
{"salud": "Gesundheit"},
{"cuestión": "Frage"},
{"déjame": "lass mich"},
{"las": "die"},
{"aqui": "hier"},
{"juntos": "gemeinsam"},
{"lejos": "weit"},
{"tengo": "ich habe"},
{"hoy": "heute"},
{"días": "Tage"},
{"nosotras": "wir"},
{"lugar": "Ort"},
{"entonces": "dann"},
{"iremos": "wir werden gehen"},
{"voy": "ich gehe"},
{"idea": "Idee"},
{"tendrá": "er/sie wird haben"},
{"problema": "Problem"},
{"caso": "Fall"},
{"base": "Basis"},
{"mujeres": "Frauen"},
{"cierto": "bestimmte"},
{"salir": "verlassen"},
{"parte": "Teil"},
{"miedo": "Angst"},
{"necesito": "ich brauche"},
{"pues": "also"},
{"poder": "können"},
{"siete": "sieben"},
{"probablemente": "wahrscheinlich"},
{"sola": "allein"},
{"cierto": "sicher"},
{"quieren": "sie wollen"},
{"con": "mit"},
{"cuanto": "so viel"},
{"quien": "wer"},
{"durante": "während"},
{"niño": "Kind"},
{"propio": "eigen"},
{"podemos": "wir können"},
{"hablo": "ich spreche"},
{"puntos": "Punkte"},
{"miembros": "Mitglieder"},
{"llama": "ruft"},
{"años": "Jahre"},
{"totalmente": "vollständig"},
{"hace": "vor"},
{"gran": "großartig"},
{"seguro": "sicher"},
{"semana": "Woche"},
{"mirar": "schauen"},
{"nivel": "Niveau"},
{"haber": "haben"},
{"usted": "Sie"},
{"hijos": "Kinder"},
{"país": "Land"},
{"porque": "weil"},
{"hago": "ich mache"},
{"importante": "wichtig"},
{"fuera": "draußen"},
{"juega": "er/sie spielt"},
{"da": "gibt"},
{"paso": "Schritt"},
{"escuela": "Schule"},
{"siquiera": "nicht einmal"},
{"verla": "sieh"},
{"puerta": "Tür"},
{"nada": "nichts"},
{"como": "wie"},
{"nuevo": "neu"},
{"casa": "Haus"},
{"hacen": "sie machen"},
{"dijo": "sagte"},
{"tipo": "Art"},
{"mejor": "besser"},
{"ciudad": "Stadt"},
{"general": "generell"},
{"dame": "gib mir"},
{"puedes": "du kannst"},
{"qué": "was"},
{"he": "habe"},
{"digo": "ich sage"},
{"lado": "Seite"},
{"pasar": "verbringen"},
{"nombre": "Name"},
{"aún": "noch"},
{"hablar": "sprechen"},
{"puedo": "ich kann"},
{"aquel": "jener"},
{"misma": "gleiche"},
{"gente": "Leute"},
{"una": "eine"},
{"mientras": "während"},
{"partir": "teilen"},
{"amigos": "Freunde"},
{"alguien": "jemand"},
{"decir": "sagen"},
{"preguntar": "fragen"},
{"aquellos": "jene"},
{"persona": "Person"},
{"duda": "Zweifel"},
{"dónde": "wohin"},
{"tal": "solch"},
{"dicho": "gesagt"},
{"tener": "haben"},
{"posible": "möglich"},
{"yo": "ich"},
{"espero": "ich hoffe"},
{"aquella": "jene"},
{"año": "Jahr"},
{"esos": "diese"},
{"cada": "jeder"},
{"para": "für"},
{"sido": "gewesen"},
{"lo": "es"},
{"amigo": "Freund"},
{"puede": "es kann"},
{"cuando": "wenn"},
{"rato": "Weile"},
{"padre": "Vater"},
{"buen": "gut"},
{"claro": "klar"},
{"bueno": "gut"},
{"ojos": "Augen"},
{"ven": "komm"},
{"fuera": "aus"},
{"otra": "andere"},
{"ti": "dich"},
{"esperanza": "Hoffnung"},
{"más": "mehr"},
{"nuestros": "unsere"},
{"todos": "alle"},
{"pueden": "sie können"},
{"pronto": "bald"},
{"algo": "etwas"},
{"sé": "ich weiß"},
{"fuerza": "Kraft"},
{"vez": "mal"},
{"verá": "er/sie wird sehen"},
{"sabes": "du weißt"},
{"me": "mir"},
{"hijo": "Sohn"},
{"fin": "Ende"},
{"llamar": "anrufen"},
{"aquello": "jenes"},
{"tiene": "hat"},
{"personas": "Personen"},
{"ustedes": "ihr"},
{"través": "durch"},
{"sí": "ja"},
{"hacer": "machen"},
{"o": "oder"},
{"necesita": "er/sie braucht"},
{"sabe": "weiß"},
{"vale": "in Ordnung"},
{"bien": "gut"},
{"y": "und"},
{"sentar": "sitzen"},
{"esto": "dieses"},
{"debe": "sollte"},
{"mi": "mein"},
{"cosas": "Dinge"},
{"continuar": "weitermachen"},
{"desde": "seit"},
{"este": "dieser"},
{"dio": "gab"},
{"tan": "so"},
{"apenas": "kaum"},
{"solo": "allein"},
{"ella": "sie"},
{"donde": "wo"},
{"estos": "diese"},
{"dice": "sagt"},
{"tu": "dein"},
{"vivir": "leben"},
{"buena": "gut"},
{"mismo": "gleich"},
{"hacia": "in Richtnug"},
{"vida": "Leben"},
{"pequeño": "klein"},
{"tenemos": "wir haben"},
{"tienen": "sie haben"},
{"amor": "Liebe"},
{"contra": "gegen"},
{"jugar": "spielen"},
{"hablando": "sprechen"},
{"mucho": "sehr"},
{"dices": "du sagst"},
{"horas": "Stunden"},
{"mujer": "Frau"},
{"sentido": "Gefühl"},
{"hacemos": "wir machen"},
{"saber": "wissen"},
{"ser": "sein"},
{"niña": "Mädchen"},
{"hola": "Hallo"},
{"mis": "meine"},
{"eso": "das"},
{"diré": "ich werde sagen"},
{"minutos": "Minuten"},
{"tema": "Thema"},
{"dad": "Vater"},
{"sólo": "nur"},
{"momento": "Moment"},
{"mes": "Monat"},
{"diciendo": "sagen"},
{"dios": "Gott"},
{"aquellas": "jene"},
{"estaré": "ich werde sein"},
{"deja": "lass es"},
{"dos": "zwei"},
{"mucho": "viel"},
{"por": "durch"},
{"ahí": "da"},
{"un": "ein"},
{"manera": "Art"},
{"trabajo": "Arbeit"},
{"buenas": "gute"},
{"haciendo": "machend"},
{"hablando": "sprechend"},
{"niño": "Junge"},
{"culpa": "Schuld"},
{"señora": "Dame"},
{"hemos": "wir haben"},
{"gracias": "danke"},
{"eso": "dies"},
{"primer": "erstes"},
{"familia": "Familie"},
{"hombre": "Mann"},
{"forma": "Form"},
{"mayor": "größer"},
{"cierta": "bestimmte"},
{"historia": "Geschichte"},
{"quién": "wer"},
{"todavía": "noch"},
{"entre": "zwischen"},
{"ver": "sehen"},
{"gusto": "Geschmack"},
{"menos": "weniger"},
{"tienes": "du hast"},
{"estás": "du bist"},
{"suerte": "Glück"},
{"hecho": "gemacht"},
{"palabra": "Wort"},
{"madre": "Mutter"},
{"vez": "Mal"},
{"probar": "probieren"},
{"vez": "Zeit"},
{"pensé": "ich dachte"},
{"habrá": "es wird geben"},
{"quieres": "du möchtest"},
{"nos": "uns"},
{"palabras": "Wörter"},
{"quiera": "er/sie möchte"},
{"meses": "Monate"},
{"él": "er"},
{"primera": "erste"},
{"ya": "bereits"},
{"dan": "sie geben"},
{"todas": "alle"},
{"espera": "Warte"},
{"los": "die"},
{"pero": "aber"},
{"cómo": "wie"},
{"seguridad": "Sicherheit"},
{"está": "ist"},
{"nunca": "nie"},
{"algunas": "einige"},
{"hay": "es gibt"},
{"oído": "gehört"},
{"hombro": "Schulter"},
{"estar": "sein"},
{"vino": "Wein"},
{"será": "es wird sein"},
{"verdad": "Wahrheit"},
{"encontrar": "finden"},
{"hasta": "bis"},
{"donde": "wohin"},
{"sin": "ohne"},
{"al": "zum"},
{"seguir": "folgen"},
{"se": "sich"},
{"sabe": "er/sie weiß"},
{"pueda": "er/sie kann"},
{"quiere": "er/sie will"},
{"después": "nach"},
{"no": "nein"},
{"nuestro": "unser"},
{"sigue": "folge"},
{"también": "auch"},
{"el": "der"},
{"tiempos": "Zeiten"},
{"incluso": "sogar"},
{"pregunta": "Frage"},
{"dar": "geben"},
{"problemas": "Probleme"},
{"sillas": "Stühle"},
{"antes": "vor"},
{"tanto": "so viel"},
{"grande": "groß"},
{"pequeña": "klein"},
{"educación": "Bildung"},
{"punto": "Punkt"},
{"hacia": "in Richtung"},
{"mío": "mein"},
{"hacerlo": "es tun"},
{"nuestra": "unsere"},
{"desde": "von"},
{"mantener": "halten"},
{"hombres": "Männer"},
{"venido": "gekommen"},
{"es": "ist"},
{"parar": "stoppen"},
{"tiempo": "Zeit"},
{"ahora": "jetzt"},
{"alguna": "irgendeine"},
{"esa": "diese"},
{"día": "Tag"},
{"vamos": "wir gehen"},
{"visto": "gesehen"},
{"aquí": "hier"},
{"mañana": "Morgen"},
{"esto": "dies"},
{"niñas": "Mädchen"},
{"sino": "sondern"},
{"comer": "essen"},
{"cosa": "Sache"},
{"dinero": "Geld"},
{"mira": "sieh"},
{"razón": "Grund"},
{"aunque": "obwohl"},
{"hablan": "sie sprechen"}
];
  
document.getElementById('start-learning').addEventListener('click', startLearning);
document.getElementById('flip-card').addEventListener('click', flipCard);
document.getElementById('next-card').addEventListener('click', nextCard);
document.getElementById('restart').addEventListener('click', restartLearning);

let start, end, direction, wordDisplay, currentWordIndex, currentWord;

function startLearning() {
    start = parseInt(document.getElementById('start').value);
    end = parseInt(document.getElementById('end').value);
    direction = document.querySelector('input[name="direction"]:checked').value;
    wordDisplay = document.getElementById('word-display');
    currentWordIndex = start;

    showWord();
}

function showWord() {
    if (currentWordIndex >= end) {
        document.getElementById('completion-area').style.display = 'block';
        return;
    }

    currentWord = vocabulary[currentWordIndex];
    if (direction === 'sp_to_ge') {
        wordDisplay.textContent = Object.keys(currentWord)[0]; // Gets the "spanish word"
    } else {
        wordDisplay.textContent = currentWord[Object.keys(currentWord)[0]]; // Gets the "german word"
    }
}

function flipCard() {
    if (currentWord) {
        if (wordDisplay.textContent === Object.keys(currentWord)[0]) {
            wordDisplay.textContent = currentWord[Object.keys(currentWord)[0]];
        } else {
            wordDisplay.textContent = Object.keys(currentWord)[0];
        }
    }
}

function nextCard() {
    currentWordIndex++;
    showWord();
}

function restartLearning() {
    currentWordIndex = start;
    document.getElementById('completion-area').style.display = 'none';
    showWord();
}
