// Shared vocabulary: each entry has a German word and its Spanish + French translations
const vocabularyData = [
  // --- Basic pronouns & articles ---
  { de: "ich", es: "yo", fr: "je" },
  { de: "du", es: "tú", fr: "tu" },
  { de: "er", es: "él", fr: "il" },
  { de: "sie", es: "ella", fr: "elle" },
  { de: "wir", es: "nosotros", fr: "nous" },
  { de: "ihr", es: "ustedes", fr: "vous" },
  { de: "sie (Plural)", es: "ellos", fr: "ils" },
  { de: "der", es: "el", fr: "le" },
  { de: "die", es: "las", fr: "les" },
  { de: "ein", es: "un", fr: "un" },
  { de: "eine", es: "una", fr: "une" },

  // --- Common verbs ---
  { de: "sein", es: "ser", fr: "être" },
  { de: "haben", es: "tener", fr: "avoir" },
  { de: "machen", es: "hacer", fr: "faire" },
  { de: "sagen", es: "decir", fr: "dire" },
  { de: "gehen", es: "ir", fr: "aller" },
  { de: "kommen", es: "venir", fr: "venir" },
  { de: "sehen", es: "ver", fr: "voir" },
  { de: "wissen", es: "saber", fr: "savoir" },
  { de: "können", es: "poder", fr: "pouvoir" },
  { de: "wollen", es: "querer", fr: "vouloir" },
  { de: "müssen", es: "deber", fr: "devoir" },
  { de: "geben", es: "dar", fr: "donner" },
  { de: "nehmen", es: "tomar", fr: "prendre" },
  { de: "finden", es: "encontrar", fr: "trouver" },
  { de: "denken", es: "pensar", fr: "penser" },
  { de: "sprechen", es: "hablar", fr: "parler" },
  { de: "lesen", es: "leer", fr: "lire" },
  { de: "schreiben", es: "escribir", fr: "écrire" },
  { de: "leben", es: "vivir", fr: "vivre" },
  { de: "essen", es: "comer", fr: "manger" },
  { de: "trinken", es: "beber", fr: "boire" },
  { de: "schlafen", es: "dormir", fr: "dormir" },
  { de: "arbeiten", es: "trabajar", fr: "travailler" },
  { de: "spielen", es: "jugar", fr: "jouer" },
  { de: "lernen", es: "aprender", fr: "apprendre" },
  { de: "verstehen", es: "entender", fr: "comprendre" },
  { de: "glauben", es: "creer", fr: "croire" },
  { de: "kennen", es: "conocer", fr: "connaître" },
  { de: "folgen", es: "seguir", fr: "suivre" },
  { de: "rufen", es: "llamar", fr: "appeler" },
  { de: "antworten", es: "responder", fr: "répondre" },
  { de: "fragen", es: "preguntar", fr: "demander" },
  { de: "brauchen", es: "necesitar", fr: "avoir besoin" },
  { de: "hoffen", es: "esperar", fr: "espérer" },
  { de: "warten", es: "esperar", fr: "attendre" },
  { de: "kaufen", es: "comprar", fr: "acheter" },
  { de: "verkaufen", es: "vender", fr: "vendre" },
  { de: "öffnen", es: "abrir", fr: "ouvrir" },
  { de: "schließen", es: "cerrar", fr: "fermer" },
  { de: "lieben", es: "amar", fr: "aimer" },
  { de: "hassen", es: "odiar", fr: "détester" },
  { de: "laufen", es: "correr", fr: "courir" },
  { de: "fahren", es: "conducir", fr: "conduire" },
  { de: "fliegen", es: "volar", fr: "voler" },
  { de: "schwimmen", es: "nadar", fr: "nager" },
  { de: "singen", es: "cantar", fr: "chanter" },
  { de: "tanzen", es: "bailar", fr: "danser" },
  { de: "kochen", es: "cocinar", fr: "cuisiner" },
  { de: "helfen", es: "ayudar", fr: "aider" },
  { de: "beginnen", es: "empezar", fr: "commencer" },
  { de: "beenden", es: "terminar", fr: "terminer" },
  { de: "vergessen", es: "olvidar", fr: "oublier" },
  { de: "erinnern", es: "recordar", fr: "se souvenir" },
  { de: "wählen", es: "elegir", fr: "choisir" },
  { de: "tragen", es: "llevar", fr: "porter" },
  { de: "sitzen", es: "sentar", fr: "s'asseoir" },
  { de: "stehen", es: "estar de pie", fr: "se lever" },
  { de: "fallen", es: "caer", fr: "tomber" },
  { de: "sterben", es: "morir", fr: "mourir" },
  { de: "geboren werden", es: "nacer", fr: "naître" },
  { de: "wachsen", es: "crecer", fr: "grandir" },
  { de: "lachen", es: "reír", fr: "rire" },
  { de: "weinen", es: "llorar", fr: "pleurer" },
  { de: "versuchen", es: "intentar", fr: "essayer" },
  { de: "zeigen", es: "mostrar", fr: "montrer" },
  { de: "erklären", es: "explicar", fr: "expliquer" },
  { de: "benutzen", es: "usar", fr: "utiliser" },
  { de: "schauen", es: "mirar", fr: "regarder" },
  { de: "hören", es: "escuchar", fr: "écouter" },
  { de: "fühlen", es: "sentir", fr: "sentir" },
  { de: "riechen", es: "oler", fr: "sentir (odeur)" },
  { de: "berühren", es: "tocar", fr: "toucher" },
  { de: "bezahlen", es: "pagar", fr: "payer" },
  { de: "zählen", es: "contar", fr: "compter" },
  { de: "ändern", es: "cambiar", fr: "changer" },
  { de: "bewegen", es: "mover", fr: "bouger" },
  { de: "stoppen", es: "parar", fr: "arrêter" },
  { de: "weitermachen", es: "continuar", fr: "continuer" },
  { de: "schicken", es: "enviar", fr: "envoyer" },
  { de: "empfangen", es: "recibir", fr: "recevoir" },
  { de: "teilen", es: "compartir", fr: "partager" },
  { de: "verlieren", es: "perder", fr: "perdre" },
  { de: "gewinnen", es: "ganar", fr: "gagner" },
  { de: "bauen", es: "construir", fr: "construire" },
  { de: "zerstören", es: "destruir", fr: "détruire" },
  { de: "reparieren", es: "reparar", fr: "réparer" },
  { de: "waschen", es: "lavar", fr: "laver" },
  { de: "trocknen", es: "secar", fr: "sécher" },
  { de: "zeichnen", es: "dibujar", fr: "dessiner" },
  { de: "malen", es: "pintar", fr: "peindre" },
  { de: "reisen", es: "viajar", fr: "voyager" },
  { de: "ankommen", es: "llegar", fr: "arriver" },
  { de: "verlassen", es: "salir", fr: "quitter" },
  { de: "bleiben", es: "quedarse", fr: "rester" },
  { de: "zurückkehren", es: "volver", fr: "revenir" },

  // --- Family ---
  { de: "Mutter", es: "madre", fr: "mère" },
  { de: "Vater", es: "padre", fr: "père" },
  { de: "Sohn", es: "hijo", fr: "fils" },
  { de: "Tochter", es: "hija", fr: "fille" },
  { de: "Bruder", es: "hermano", fr: "frère" },
  { de: "Schwester", es: "hermana", fr: "sœur" },
  { de: "Großvater", es: "abuelo", fr: "grand-père" },
  { de: "Großmutter", es: "abuela", fr: "grand-mère" },
  { de: "Onkel", es: "tío", fr: "oncle" },
  { de: "Tante", es: "tía", fr: "tante" },
  { de: "Cousin", es: "primo", fr: "cousin" },
  { de: "Cousine", es: "prima", fr: "cousine" },
  { de: "Ehemann", es: "marido", fr: "mari" },
  { de: "Ehefrau", es: "esposa", fr: "épouse" },
  { de: "Eltern", es: "padres", fr: "parents" },
  { de: "Kind", es: "niño", fr: "enfant" },
  { de: "Kinder", es: "niños", fr: "enfants" },
  { de: "Familie", es: "familia", fr: "famille" },
  { de: "Freund", es: "amigo", fr: "ami" },
  { de: "Freundin", es: "amiga", fr: "amie" },
  { de: "Mann", es: "hombre", fr: "homme" },
  { de: "Frau", es: "mujer", fr: "femme" },
  { de: "Mädchen", es: "chica", fr: "fille" },
  { de: "Junge", es: "chico", fr: "garçon" },
  { de: "Baby", es: "bebé", fr: "bébé" },
  { de: "Person", es: "persona", fr: "personne" },
  { de: "Leute", es: "gente", fr: "gens" },
  { de: "Nachbar", es: "vecino", fr: "voisin" },

  // --- Body ---
  { de: "Kopf", es: "cabeza", fr: "tête" },
  { de: "Hand", es: "mano", fr: "main" },
  { de: "Hände", es: "manos", fr: "mains" },
  { de: "Auge", es: "ojo", fr: "œil" },
  { de: "Augen", es: "ojos", fr: "yeux" },
  { de: "Ohr", es: "oreja", fr: "oreille" },
  { de: "Nase", es: "nariz", fr: "nez" },
  { de: "Mund", es: "boca", fr: "bouche" },
  { de: "Herz", es: "corazón", fr: "cœur" },
  { de: "Fuß", es: "pie", fr: "pied" },
  { de: "Bein", es: "pierna", fr: "jambe" },
  { de: "Arm", es: "brazo", fr: "bras" },
  { de: "Finger", es: "dedo", fr: "doigt" },
  { de: "Schulter", es: "hombro", fr: "épaule" },
  { de: "Rücken", es: "espalda", fr: "dos" },
  { de: "Bauch", es: "estómago", fr: "ventre" },
  { de: "Haar", es: "pelo", fr: "cheveux" },
  { de: "Zahn", es: "diente", fr: "dent" },
  { de: "Zähne", es: "dientes", fr: "dents" },
  { de: "Haut", es: "piel", fr: "peau" },
  { de: "Blut", es: "sangre", fr: "sang" },
  { de: "Knochen", es: "hueso", fr: "os" },

  // --- Nature & World ---
  { de: "Welt", es: "mundo", fr: "monde" },
  { de: "Erde", es: "tierra", fr: "terre" },
  { de: "Himmel", es: "cielo", fr: "ciel" },
  { de: "Sonne", es: "sol", fr: "soleil" },
  { de: "Mond", es: "luna", fr: "lune" },
  { de: "Stern", es: "estrella", fr: "étoile" },
  { de: "Wasser", es: "agua", fr: "eau" },
  { de: "Feuer", es: "fuego", fr: "feu" },
  { de: "Luft", es: "aire", fr: "air" },
  { de: "Wind", es: "viento", fr: "vent" },
  { de: "Regen", es: "lluvia", fr: "pluie" },
  { de: "Schnee", es: "nieve", fr: "neige" },
  { de: "Meer", es: "mar", fr: "mer" },
  { de: "See", es: "lago", fr: "lac" },
  { de: "Fluss", es: "río", fr: "rivière" },
  { de: "Berg", es: "montaña", fr: "montagne" },
  { de: "Wald", es: "bosque", fr: "forêt" },
  { de: "Baum", es: "árbol", fr: "arbre" },
  { de: "Blume", es: "flor", fr: "fleur" },
  { de: "Gras", es: "hierba", fr: "herbe" },
  { de: "Stein", es: "piedra", fr: "pierre" },
  { de: "Sand", es: "arena", fr: "sable" },
  { de: "Wolke", es: "nube", fr: "nuage" },
  { de: "Sturm", es: "tormenta", fr: "tempête" },
  { de: "Insel", es: "isla", fr: "île" },
  { de: "Strand", es: "playa", fr: "plage" },
  { de: "Wüste", es: "desierto", fr: "désert" },
  { de: "Licht", es: "luz", fr: "lumière" },
  { de: "Schatten", es: "sombra", fr: "ombre" },

  // --- Animals ---
  { de: "Hund", es: "perro", fr: "chien" },
  { de: "Katze", es: "gato", fr: "chat" },
  { de: "Pferd", es: "caballo", fr: "cheval" },
  { de: "Vogel", es: "pájaro", fr: "oiseau" },
  { de: "Fisch", es: "pez", fr: "poisson" },
  { de: "Kuh", es: "vaca", fr: "vache" },
  { de: "Schwein", es: "cerdo", fr: "cochon" },
  { de: "Schaf", es: "oveja", fr: "mouton" },
  { de: "Huhn", es: "pollo", fr: "poulet" },
  { de: "Bär", es: "oso", fr: "ours" },
  { de: "Löwe", es: "león", fr: "lion" },
  { de: "Tiger", es: "tigre", fr: "tigre" },
  { de: "Elefant", es: "elefante", fr: "éléphant" },
  { de: "Affe", es: "mono", fr: "singe" },
  { de: "Schlange", es: "serpiente", fr: "serpent" },
  { de: "Maus", es: "ratón", fr: "souris" },
  { de: "Kaninchen", es: "conejo", fr: "lapin" },
  { de: "Frosch", es: "rana", fr: "grenouille" },
  { de: "Schmetterling", es: "mariposa", fr: "papillon" },
  { de: "Ameise", es: "hormiga", fr: "fourmi" },

  // --- Food & Drink ---
  { de: "Brot", es: "pan", fr: "pain" },
  { de: "Wein", es: "vino", fr: "vin" },
  { de: "Bier", es: "cerveza", fr: "bière" },
  { de: "Milch", es: "leche", fr: "lait" },
  { de: "Käse", es: "queso", fr: "fromage" },
  { de: "Fleisch", es: "carne", fr: "viande" },
  { de: "Reis", es: "arroz", fr: "riz" },
  { de: "Ei", es: "huevo", fr: "œuf" },
  { de: "Butter", es: "mantequilla", fr: "beurre" },
  { de: "Zucker", es: "azúcar", fr: "sucre" },
  { de: "Salz", es: "sal", fr: "sel" },
  { de: "Obst", es: "fruta", fr: "fruit" },
  { de: "Gemüse", es: "verdura", fr: "légume" },
  { de: "Apfel", es: "manzana", fr: "pomme" },
  { de: "Orange", es: "naranja", fr: "orange" },
  { de: "Banane", es: "plátano", fr: "banane" },
  { de: "Tomate", es: "tomate", fr: "tomate" },
  { de: "Kartoffel", es: "patata", fr: "pomme de terre" },
  { de: "Fisch (Essen)", es: "pescado", fr: "poisson" },
  { de: "Suppe", es: "sopa", fr: "soupe" },
  { de: "Kuchen", es: "pastel", fr: "gâteau" },
  { de: "Schokolade", es: "chocolate", fr: "chocolat" },
  { de: "Kaffee", es: "café", fr: "café" },
  { de: "Tee", es: "té", fr: "thé" },
  { de: "Saft", es: "zumo", fr: "jus" },
  { de: "Eis", es: "helado", fr: "glace" },

  // --- Places & Buildings ---
  { de: "Haus", es: "casa", fr: "maison" },
  { de: "Stadt", es: "ciudad", fr: "ville" },
  { de: "Land", es: "país", fr: "pays" },
  { de: "Schule", es: "escuela", fr: "école" },
  { de: "Kirche", es: "iglesia", fr: "église" },
  { de: "Krankenhaus", es: "hospital", fr: "hôpital" },
  { de: "Flughafen", es: "aeropuerto", fr: "aéroport" },
  { de: "Bahnhof", es: "estación", fr: "gare" },
  { de: "Restaurant", es: "restaurante", fr: "restaurant" },
  { de: "Hotel", es: "hotel", fr: "hôtel" },
  { de: "Geschäft", es: "tienda", fr: "magasin" },
  { de: "Markt", es: "mercado", fr: "marché" },
  { de: "Museum", es: "museo", fr: "musée" },
  { de: "Bibliothek", es: "biblioteca", fr: "bibliothèque" },
  { de: "Universität", es: "universidad", fr: "université" },
  { de: "Büro", es: "oficina", fr: "bureau" },
  { de: "Park", es: "parque", fr: "parc" },
  { de: "Straße", es: "calle", fr: "rue" },
  { de: "Brücke", es: "puente", fr: "pont" },
  { de: "Platz", es: "plaza", fr: "place" },
  { de: "Garten", es: "jardín", fr: "jardin" },
  { de: "Tür", es: "puerta", fr: "porte" },
  { de: "Fenster", es: "ventana", fr: "fenêtre" },
  { de: "Zimmer", es: "habitación", fr: "chambre" },
  { de: "Küche", es: "cocina", fr: "cuisine" },
  { de: "Schlafzimmer", es: "dormitorio", fr: "chambre à coucher" },
  { de: "Badezimmer", es: "baño", fr: "salle de bain" },

  // --- Time ---
  { de: "Zeit", es: "tiempo", fr: "temps" },
  { de: "Tag", es: "día", fr: "jour" },
  { de: "Nacht", es: "noche", fr: "nuit" },
  { de: "Morgen", es: "mañana", fr: "matin" },
  { de: "Nachmittag", es: "tarde", fr: "après-midi" },
  { de: "Abend", es: "noche", fr: "soir" },
  { de: "Stunde", es: "hora", fr: "heure" },
  { de: "Minute", es: "minuto", fr: "minute" },
  { de: "Sekunde", es: "segundo", fr: "seconde" },
  { de: "Woche", es: "semana", fr: "semaine" },
  { de: "Monat", es: "mes", fr: "mois" },
  { de: "Jahr", es: "año", fr: "an" },
  { de: "heute", es: "hoy", fr: "aujourd'hui" },
  { de: "morgen", es: "mañana", fr: "demain" },
  { de: "gestern", es: "ayer", fr: "hier" },
  { de: "jetzt", es: "ahora", fr: "maintenant" },
  { de: "immer", es: "siempre", fr: "toujours" },
  { de: "nie", es: "nunca", fr: "jamais" },
  { de: "bald", es: "pronto", fr: "bientôt" },
  { de: "spät", es: "tarde", fr: "tard" },
  { de: "früh", es: "temprano", fr: "tôt" },

  // --- Days of the week ---
  { de: "Montag", es: "lunes", fr: "lundi" },
  { de: "Dienstag", es: "martes", fr: "mardi" },
  { de: "Mittwoch", es: "miércoles", fr: "mercredi" },
  { de: "Donnerstag", es: "jueves", fr: "jeudi" },
  { de: "Freitag", es: "viernes", fr: "vendredi" },
  { de: "Samstag", es: "sábado", fr: "samedi" },
  { de: "Sonntag", es: "domingo", fr: "dimanche" },

  // --- Months ---
  { de: "Januar", es: "enero", fr: "janvier" },
  { de: "Februar", es: "febrero", fr: "février" },
  { de: "März", es: "marzo", fr: "mars" },
  { de: "April", es: "abril", fr: "avril" },
  { de: "Mai", es: "mayo", fr: "mai" },
  { de: "Juni", es: "junio", fr: "juin" },
  { de: "Juli", es: "julio", fr: "juillet" },
  { de: "August", es: "agosto", fr: "août" },
  { de: "September", es: "septiembre", fr: "septembre" },
  { de: "Oktober", es: "octubre", fr: "octobre" },
  { de: "November", es: "noviembre", fr: "novembre" },
  { de: "Dezember", es: "diciembre", fr: "décembre" },

  // --- Numbers ---
  { de: "null", es: "cero", fr: "zéro" },
  { de: "eins", es: "uno", fr: "un" },
  { de: "zwei", es: "dos", fr: "deux" },
  { de: "drei", es: "tres", fr: "trois" },
  { de: "vier", es: "cuatro", fr: "quatre" },
  { de: "fünf", es: "cinco", fr: "cinq" },
  { de: "sechs", es: "seis", fr: "six" },
  { de: "sieben", es: "siete", fr: "sept" },
  { de: "acht", es: "ocho", fr: "huit" },
  { de: "neun", es: "nueve", fr: "neuf" },
  { de: "zehn", es: "diez", fr: "dix" },
  { de: "zwanzig", es: "veinte", fr: "vingt" },
  { de: "dreißig", es: "treinta", fr: "trente" },
  { de: "vierzig", es: "cuarenta", fr: "quarante" },
  { de: "fünfzig", es: "cincuenta", fr: "cinquante" },
  { de: "hundert", es: "cien", fr: "cent" },
  { de: "tausend", es: "mil", fr: "mille" },
  { de: "eine Million", es: "un millón", fr: "un million" },

  // --- Colors ---
  { de: "rot", es: "rojo", fr: "rouge" },
  { de: "blau", es: "azul", fr: "bleu" },
  { de: "grün", es: "verde", fr: "vert" },
  { de: "gelb", es: "amarillo", fr: "jaune" },
  { de: "schwarz", es: "negro", fr: "noir" },
  { de: "weiß", es: "blanco", fr: "blanc" },
  { de: "grau", es: "gris", fr: "gris" },
  { de: "braun", es: "marrón", fr: "marron" },
  { de: "rosa", es: "rosa", fr: "rose" },
  { de: "orange", es: "naranja", fr: "orange" },
  { de: "lila", es: "morado", fr: "violet" },

  // --- Adjectives ---
  { de: "groß", es: "grande", fr: "grand" },
  { de: "klein", es: "pequeño", fr: "petit" },
  { de: "gut", es: "bueno", fr: "bon" },
  { de: "schlecht", es: "malo", fr: "mauvais" },
  { de: "neu", es: "nuevo", fr: "nouveau" },
  { de: "alt", es: "viejo", fr: "vieux" },
  { de: "jung", es: "joven", fr: "jeune" },
  { de: "schön", es: "bonito", fr: "beau" },
  { de: "hässlich", es: "feo", fr: "laid" },
  { de: "schnell", es: "rápido", fr: "rapide" },
  { de: "langsam", es: "lento", fr: "lent" },
  { de: "stark", es: "fuerte", fr: "fort" },
  { de: "schwach", es: "débil", fr: "faible" },
  { de: "leicht", es: "fácil", fr: "facile" },
  { de: "schwer", es: "difícil", fr: "difficile" },
  { de: "heiß", es: "caliente", fr: "chaud" },
  { de: "kalt", es: "frío", fr: "froid" },
  { de: "warm", es: "cálido", fr: "tiède" },
  { de: "nass", es: "mojado", fr: "mouillé" },
  { de: "trocken", es: "seco", fr: "sec" },
  { de: "lang", es: "largo", fr: "long" },
  { de: "kurz", es: "corto", fr: "court" },
  { de: "breit", es: "ancho", fr: "large" },
  { de: "eng", es: "estrecho", fr: "étroit" },
  { de: "hoch", es: "alto", fr: "haut" },
  { de: "tief", es: "profundo", fr: "profond" },
  { de: "laut", es: "ruidoso", fr: "bruyant" },
  { de: "leise", es: "silencioso", fr: "silencieux" },
  { de: "hell", es: "claro", fr: "clair" },
  { de: "dunkel", es: "oscuro", fr: "sombre" },
  { de: "reich", es: "rico", fr: "riche" },
  { de: "arm", es: "pobre", fr: "pauvre" },
  { de: "glücklich", es: "feliz", fr: "heureux" },
  { de: "traurig", es: "triste", fr: "triste" },
  { de: "müde", es: "cansado", fr: "fatigué" },
  { de: "hungrig", es: "hambriento", fr: "affamé" },
  { de: "durstig", es: "sediento", fr: "assoiffé" },
  { de: "krank", es: "enfermo", fr: "malade" },
  { de: "gesund", es: "sano", fr: "sain" },
  { de: "wichtig", es: "importante", fr: "important" },
  { de: "möglich", es: "posible", fr: "possible" },
  { de: "sicher", es: "seguro", fr: "sûr" },
  { de: "frei", es: "libre", fr: "libre" },
  { de: "voll", es: "lleno", fr: "plein" },
  { de: "leer", es: "vacío", fr: "vide" },
  { de: "richtig", es: "correcto", fr: "correct" },
  { de: "falsch", es: "falso", fr: "faux" },
  { de: "gleich", es: "igual", fr: "égal" },
  { de: "anders", es: "diferente", fr: "différent" },
  { de: "einfach", es: "simple", fr: "simple" },
  { de: "besser", es: "mejor", fr: "meilleur" },
  { de: "schlimmer", es: "peor", fr: "pire" },

  // --- Common nouns ---
  { de: "Arbeit", es: "trabajo", fr: "travail" },
  { de: "Geld", es: "dinero", fr: "argent" },
  { de: "Liebe", es: "amor", fr: "amour" },
  { de: "Leben", es: "vida", fr: "vie" },
  { de: "Tod", es: "muerte", fr: "mort" },
  { de: "Wahrheit", es: "verdad", fr: "vérité" },
  { de: "Lüge", es: "mentira", fr: "mensonge" },
  { de: "Angst", es: "miedo", fr: "peur" },
  { de: "Hoffnung", es: "esperanza", fr: "espoir" },
  { de: "Glück", es: "suerte", fr: "chance" },
  { de: "Freiheit", es: "libertad", fr: "liberté" },
  { de: "Frieden", es: "paz", fr: "paix" },
  { de: "Krieg", es: "guerra", fr: "guerre" },
  { de: "Geschichte", es: "historia", fr: "histoire" },
  { de: "Kraft", es: "fuerza", fr: "force" },
  { de: "Macht", es: "poder", fr: "pouvoir" },
  { de: "Recht", es: "derecho", fr: "droit" },
  { de: "Gesetz", es: "ley", fr: "loi" },
  { de: "Wort", es: "palabra", fr: "mot" },
  { de: "Sprache", es: "idioma", fr: "langue" },
  { de: "Buch", es: "libro", fr: "livre" },
  { de: "Brief", es: "carta", fr: "lettre" },
  { de: "Zeitung", es: "periódico", fr: "journal" },
  { de: "Film", es: "película", fr: "film" },
  { de: "Musik", es: "música", fr: "musique" },
  { de: "Lied", es: "canción", fr: "chanson" },
  { de: "Bild", es: "imagen", fr: "image" },
  { de: "Foto", es: "foto", fr: "photo" },
  { de: "Idee", es: "idea", fr: "idée" },
  { de: "Problem", es: "problema", fr: "problème" },
  { de: "Frage", es: "pregunta", fr: "question" },
  { de: "Antwort", es: "respuesta", fr: "réponse" },
  { de: "Beispiel", es: "ejemplo", fr: "exemple" },
  { de: "Grund", es: "razón", fr: "raison" },
  { de: "Ende", es: "fin", fr: "fin" },
  { de: "Anfang", es: "principio", fr: "début" },
  { de: "Weg", es: "camino", fr: "chemin" },
  { de: "Teil", es: "parte", fr: "partie" },
  { de: "Seite", es: "lado", fr: "côté" },
  { de: "Mitte", es: "centro", fr: "centre" },
  { de: "Form", es: "forma", fr: "forme" },
  { de: "Art", es: "tipo", fr: "type" },
  { de: "Nummer", es: "número", fr: "numéro" },
  { de: "Name", es: "nombre", fr: "nom" },
  { de: "Stimme", es: "voz", fr: "voix" },
  { de: "Gesicht", es: "cara", fr: "visage" },
  { de: "Traum", es: "sueño", fr: "rêve" },
  { de: "Schlüssel", es: "llave", fr: "clé" },
  { de: "Telefon", es: "teléfono", fr: "téléphone" },
  { de: "Computer", es: "ordenador", fr: "ordinateur" },
  { de: "Auto", es: "coche", fr: "voiture" },
  { de: "Zug", es: "tren", fr: "train" },
  { de: "Flugzeug", es: "avión", fr: "avion" },
  { de: "Schiff", es: "barco", fr: "bateau" },
  { de: "Fahrrad", es: "bicicleta", fr: "vélo" },
  { de: "Kleidung", es: "ropa", fr: "vêtements" },
  { de: "Hemd", es: "camisa", fr: "chemise" },
  { de: "Hose", es: "pantalón", fr: "pantalon" },
  { de: "Schuh", es: "zapato", fr: "chaussure" },
  { de: "Hut", es: "sombrero", fr: "chapeau" },
  { de: "Tasche", es: "bolsa", fr: "sac" },
  { de: "Uhr", es: "reloj", fr: "montre" },
  { de: "Stuhl", es: "silla", fr: "chaise" },
  { de: "Tisch", es: "mesa", fr: "table" },
  { de: "Bett", es: "cama", fr: "lit" },
  { de: "Lampe", es: "lámpara", fr: "lampe" },
  { de: "Spiegel", es: "espejo", fr: "miroir" },
  { de: "Treppe", es: "escalera", fr: "escalier" },
  { de: "Dach", es: "techo", fr: "toit" },
  { de: "Boden", es: "suelo", fr: "sol" },
  { de: "Wand", es: "pared", fr: "mur" },
  { de: "Geschenk", es: "regalo", fr: "cadeau" },
  { de: "Spiel", es: "juego", fr: "jeu" },
  { de: "Mannschaft", es: "equipo", fr: "équipe" },
  { de: "Preis", es: "precio", fr: "prix" },
  { de: "Gesundheit", es: "salud", fr: "santé" },
  { de: "Bildung", es: "educación", fr: "éducation" },
  { de: "Sicherheit", es: "seguridad", fr: "sécurité" },
  { de: "Regierung", es: "gobierno", fr: "gouvernement" },

  // --- Prepositions & Conjunctions ---
  { de: "mit", es: "con", fr: "avec" },
  { de: "ohne", es: "sin", fr: "sans" },
  { de: "für", es: "para", fr: "pour" },
  { de: "gegen", es: "contra", fr: "contre" },
  { de: "zwischen", es: "entre", fr: "entre" },
  { de: "über", es: "sobre", fr: "sur" },
  { de: "unter", es: "debajo", fr: "sous" },
  { de: "vor", es: "antes", fr: "avant" },
  { de: "nach", es: "después", fr: "après" },
  { de: "seit", es: "desde", fr: "depuis" },
  { de: "bis", es: "hasta", fr: "jusqu'à" },
  { de: "während", es: "durante", fr: "pendant" },
  { de: "neben", es: "al lado de", fr: "à côté de" },
  { de: "und", es: "y", fr: "et" },
  { de: "oder", es: "o", fr: "ou" },
  { de: "aber", es: "pero", fr: "mais" },
  { de: "weil", es: "porque", fr: "parce que" },
  { de: "obwohl", es: "aunque", fr: "bien que" },
  { de: "wenn", es: "si", fr: "si" },
  { de: "dass", es: "que", fr: "que" },
  { de: "auch", es: "también", fr: "aussi" },
  { de: "sondern", es: "sino", fr: "mais (plutôt)" },
  { de: "noch", es: "todavía", fr: "encore" },
  { de: "schon", es: "ya", fr: "déjà" },

  // --- Adverbs & Common Words ---
  { de: "hier", es: "aquí", fr: "ici" },
  { de: "dort", es: "allí", fr: "là-bas" },
  { de: "wo", es: "dónde", fr: "où" },
  { de: "wann", es: "cuándo", fr: "quand" },
  { de: "wie", es: "cómo", fr: "comment" },
  { de: "warum", es: "por qué", fr: "pourquoi" },
  { de: "was", es: "qué", fr: "quoi" },
  { de: "wer", es: "quién", fr: "qui" },
  { de: "ja", es: "sí", fr: "oui" },
  { de: "nein", es: "no", fr: "non" },
  { de: "nicht", es: "no", fr: "ne...pas" },
  { de: "sehr", es: "muy", fr: "très" },
  { de: "mehr", es: "más", fr: "plus" },
  { de: "weniger", es: "menos", fr: "moins" },
  { de: "viel", es: "mucho", fr: "beaucoup" },
  { de: "wenig", es: "poco", fr: "peu" },
  { de: "alles", es: "todo", fr: "tout" },
  { de: "nichts", es: "nada", fr: "rien" },
  { de: "etwas", es: "algo", fr: "quelque chose" },
  { de: "jemand", es: "alguien", fr: "quelqu'un" },
  { de: "niemand", es: "nadie", fr: "personne" },
  { de: "nur", es: "sólo", fr: "seulement" },
  { de: "sogar", es: "incluso", fr: "même" },
  { de: "vielleicht", es: "quizás", fr: "peut-être" },
  { de: "wahrscheinlich", es: "probablemente", fr: "probablement" },
  { de: "zusammen", es: "juntos", fr: "ensemble" },
  { de: "allein", es: "solo", fr: "seul" },
  { de: "danke", es: "gracias", fr: "merci" },
  { de: "bitte", es: "por favor", fr: "s'il vous plaît" },
  { de: "Entschuldigung", es: "perdón", fr: "pardon" },
  { de: "Hallo", es: "hola", fr: "bonjour" },
  { de: "Tschüss", es: "adiós", fr: "au revoir" },
  { de: "Guten Morgen", es: "buenos días", fr: "bonjour" },
  { de: "Gute Nacht", es: "buenas noches", fr: "bonne nuit" },
  { de: "Willkommen", es: "bienvenido", fr: "bienvenue" },
  { de: "Prost", es: "salud", fr: "santé" },
  { de: "Hilfe", es: "ayuda", fr: "aide" },
  { de: "Geburtstag", es: "cumpleaños", fr: "anniversaire" },
  { de: "Weihnachten", es: "Navidad", fr: "Noël" },

  // --- Professions ---
  { de: "Arzt", es: "médico", fr: "médecin" },
  { de: "Lehrer", es: "profesor", fr: "professeur" },
  { de: "Polizist", es: "policía", fr: "policier" },
  { de: "Anwalt", es: "abogado", fr: "avocat" },
  { de: "Ingenieur", es: "ingeniero", fr: "ingénieur" },
  { de: "Koch", es: "cocinero", fr: "cuisinier" },
  { de: "Kellner", es: "camarero", fr: "serveur" },
  { de: "Verkäufer", es: "vendedor", fr: "vendeur" },
  { de: "Fahrer", es: "conductor", fr: "chauffeur" },
  { de: "Künstler", es: "artista", fr: "artiste" },
  { de: "Schriftsteller", es: "escritor", fr: "écrivain" },
  { de: "Journalist", es: "periodista", fr: "journaliste" },
  { de: "Bauer", es: "granjero", fr: "fermier" },
  { de: "Soldat", es: "soldado", fr: "soldat" },
  { de: "Pilot", es: "piloto", fr: "pilote" },

  // --- Emotions & States ---
  { de: "Freude", es: "alegría", fr: "joie" },
  { de: "Trauer", es: "tristeza", fr: "tristesse" },
  { de: "Wut", es: "ira", fr: "colère" },
  { de: "Überraschung", es: "sorpresa", fr: "surprise" },
  { de: "Langeweile", es: "aburrimiento", fr: "ennui" },
  { de: "Stolz", es: "orgullo", fr: "fierté" },
  { de: "Scham", es: "vergüenza", fr: "honte" },
  { de: "Eifersucht", es: "celos", fr: "jalousie" },
  { de: "Vertrauen", es: "confianza", fr: "confiance" },
  { de: "Zweifel", es: "duda", fr: "doute" },

  // --- Weather ---
  { de: "Wetter", es: "tiempo", fr: "temps" },
  { de: "Gewitter", es: "tormenta", fr: "orage" },
  { de: "Nebel", es: "niebla", fr: "brouillard" },
  { de: "Eis (gefroren)", es: "hielo", fr: "glace" },
  { de: "Regenbogen", es: "arcoíris", fr: "arc-en-ciel" },
  { de: "Temperatur", es: "temperatura", fr: "température" },

  // --- More everyday words ---
  { de: "Schritt", es: "paso", fr: "pas" },
  { de: "Ort", es: "lugar", fr: "lieu" },
  { de: "Punkt", es: "punto", fr: "point" },
  { de: "Moment", es: "momento", fr: "moment" },
  { de: "Sache", es: "cosa", fr: "chose" },
  { de: "Ding", es: "cosa", fr: "truc" },
  { de: "Thema", es: "tema", fr: "sujet" },
  { de: "Fall", es: "caso", fr: "cas" },
  { de: "Wert", es: "valor", fr: "valeur" },
  { de: "Nachricht", es: "mensaje", fr: "message" },
  { de: "Ergebnis", es: "resultado", fr: "résultat" },
  { de: "Fehler", es: "error", fr: "erreur" },
  { de: "Erfolg", es: "éxito", fr: "succès" },
  { de: "Zukunft", es: "futuro", fr: "avenir" },
  { de: "Vergangenheit", es: "pasado", fr: "passé" },
  { de: "Gegenwart", es: "presente", fr: "présent" },
  { de: "Versprechen", es: "promesa", fr: "promesse" },
  { de: "Geheimnis", es: "secreto", fr: "secret" },
  { de: "Abenteuer", es: "aventura", fr: "aventure" },
  { de: "Erfahrung", es: "experiencia", fr: "expérience" },
  { de: "Erinnerung", es: "recuerdo", fr: "souvenir" },
  { de: "Entscheidung", es: "decisión", fr: "décision" },
  { de: "Meinung", es: "opinión", fr: "opinion" },
  { de: "Unterschied", es: "diferencia", fr: "différence" },
  { de: "Beziehung", es: "relación", fr: "relation" },
  { de: "Gefühl", es: "sentimiento", fr: "sentiment" },
  { de: "Gedanke", es: "pensamiento", fr: "pensée" },
  { de: "Ziel", es: "objetivo", fr: "objectif" },
  { de: "Regel", es: "regla", fr: "règle" },
  { de: "Aufgabe", es: "tarea", fr: "tâche" },
  { de: "Lösung", es: "solución", fr: "solution" },
  { de: "Möglichkeit", es: "posibilidad", fr: "possibilité" },
  { de: "Wirklichkeit", es: "realidad", fr: "réalité" },
  { de: "Gesellschaft", es: "sociedad", fr: "société" },
  { de: "Kultur", es: "cultura", fr: "culture" },
  { de: "Natur", es: "naturaleza", fr: "nature" },
  { de: "Wissenschaft", es: "ciencia", fr: "science" },
  { de: "Kunst", es: "arte", fr: "art" },
  { de: "Sport", es: "deporte", fr: "sport" },
  { de: "Himmel (Paradies)", es: "paraíso", fr: "paradis" },
  { de: "Hölle", es: "infierno", fr: "enfer" },
  { de: "Gott", es: "dios", fr: "dieu" },
  { de: "Seele", es: "alma", fr: "âme" },
  { de: "Schuld", es: "culpa", fr: "culpabilité" },
  { de: "Rechnung", es: "cuenta", fr: "facture" },
  { de: "Geschmack", es: "gusto", fr: "goût" },
];
